### ISSUE TITLE
Implement CORS-support

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#1]
Allow defining accepted origins on a per-channel and/or global level. Special case for all origins should also be added, basically telling the hub to simply respond with the value sent in the `Origin` header directly.

Note: It's important that the CORS-implementation sends
`Access-Control-Allow-Headers: Last-Event-ID` as a header.

**Comment by olesku** [comment]
Implemented in 0b4d16f0a1c5906acaceff808bcac755d061f52f
