### ISSUE TITLE
Configurable "ping"

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#3]
Most SSE writeups I've seen suggest that you send a ping to clients if there has not been any activity on the socket for a given amount of time, to ensure that the client doesn't consider it a read timeout and close the connection.

I don't think this needs to be configured on a per-path basis, so simply setting a global interval will probably be good enough.

My [sse-channel library](https://github.com/rexxars/sse-channel/blob/master/lib/sse-channel.js#L161) implements this as simply `:\n` (lines starting with `:` are considered "comments" by SSE-clients).

**Comment by olesku** [comment]
Implemented and configurable with server.pingInterval
