### ISSUE TITLE
Send preamble to polyfilled clients

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#4]
Internet Explorer has a problem receiving data when using XDomainRequest before it has received 2KB of data. The polyfills that account for this send a query parameter, `evs_preamble` to inform the server about this so it can respond with some initial data.

A good bet would bet would be to send a `:` characters followed by 2KB of data and a newline character, to make sure the client treats it as a comment and doesn't try to parse it somehow.

**Comment by olesku** [comment]
Implemented in c3c2393776b95e3854aa3083d154591f61dbed83
