### ISSUE TITLE
Send history for channel when client reconnects

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#5]
When a client disconnects because of network issues or a timeout of some sort, the client will reconnect with an HTTP header (`Last-Event-ID`) specifying (obviously) the ID of the last event that was received. It's then up to the server (the hub) to send back all messages the client has lost since the disconnect.

We also need to check for the query parameters `evs_last_event_id` and `lastEventId`, which various polyfills use instead of the header when IE connects cross-domain.

The messages that are returned are simply sent as regular messages as if they were "new", but obviously only to the client that requested them.

**Comment by rexxars** [comment]
After some discussion today, I think we landed on skipping the ZMQ step and instead maintaining a local history which is populated on startup. The header/query string stuff is still relevant, so I'll rename and reword this task a bit.

**Comment by olesku** [comment]
Implemented in commit 2e07b9d4939a5538f8c278664f86f5f860b4013d
