### ISSUE TITLE
Initialize requests with correct headers/data

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#6]
Requests to a channel should get a response with the following headers:

```
Content-Type: text/event-stream
Cache-Control: no-cache
Connection: keep-alive
```

See also #1 (CORS-headers).

It's also suggested that you write an initial "comment"-chunk, for instance:

```
:ok\n\n
```

If we have a global "retry interval" setting on the hub, we should also issue that:

```
retry: <milliseconds>\n
```

**Comment by olesku** [comment]
Implemented in 6551a112f3f8b6de6321a31d450f2d0db9811aa2
