### ISSUE TITLE
Define how "config endpoint" response looks

### ISSUE THREAD

**Issue by rexxars** [vgno/ssehub#8]
Suggestion:

``` json
{
    "global": {
        "allowedOrigins": ["https://some.service.no/"],
        "allowUndefinedChannels": true,
        "historyLength": 500
    },

    "channels": [{
        "path": "/some/path",
        "allowedOrigins": ["https://some.host"],
        "historyUrl": "https://some.url/which/talks/json",
        "historyLength": 50
    }, {
        "path": "/otherpath",
        "allowedOrigins": false
    }]
}
```

`allowedOrigins` is used in the CORS handling - `false` means do not allow any cross-origin requests, array of values means use those specific origins. If it's not set for a specific channel, use the global value.

`allowUndefinedChannels` sets whether the hub should allow connections on channels that are not in the channels array.

`historyUrl` specifies an HTTP endpoint where the hub can go to fetch the initial history it should preload into memory.

`historyLength` defines (on a global/channel level) how many messages it should keep in memory.

**Comment by olesku** [comment]
This looks like a format that covers what we need in a good way.
Let's stick to it.

I will start to implement it in the hub
